Dog.create(name: "Wimpy", breed: "Border Collie Mix", description: "Easily excitable")
Dog.create(name: "Desdemona", breed: "Pitbull Mix", description: "The Skoog")
Dog.create(name: "Lola", breed: "Pitbull Mix", description: "Smart and dumb at the same time")
Dog.create(name: "Violet", breed: "Border Collie Mix", description: "Destructive when bored")
Dog.create(name: "Lucky", breed: "Yellow Lab", description: "Crazy and fun")
Dog.create(name: "Cooper", breed: "Yorkie", description: "Pretentious popped collar puppy")
Dog.create(name: "Nakatsu", breed: "Shiba Inu", description: "Chucky Boy")
Dog.create(name: "Mei", breed: "Pom-Mix", description: "Tiny Lady")
Dog.create(name: "Pongo", breed: "Blue Heeler", description: "Likes to play with her bones")
Dog.create(name: "", breed: "", description: "")
